# -*- coding: utf-8 -*-
# This file is auto-generated with the script make_family.py
# if you find something wrong please fix the script
# otherwise your edit will be overwritten
#
from pywikibot import family
from pywikibot.tools import deprecated

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'wikitolearn'
        self.langs = {
            'it': 'it.wikitolearn.org',
            'en': 'en.wikitolearn.org',
            'de': 'de.wikitolearn.org',
            'es': 'es.wikitolearn.org',
            'fr': 'fr.wikitolearn.org',
            'pt': 'pt.wikitolearn.org',
            'sv': 'sv.wikitolearn.org',
            'ca': 'ca.wikitolearn.org',
            'meta': 'meta.wikitolearn.org',
            'pool': 'pool.wikitolearn.org',
            'devit': 'it.wikitolearn.vodka',
            'deven': 'en.wikitolearn.vodka',
            'devde': 'de.wikitolearn.vodka',
            'deves': 'es.wikitolearn.vodka',
            'devfr': 'fr.wikitolearn.vodka',
            'devpt': 'pt.wikitolearn.vodka',
            'devsv': 'sv.wikitolearn.vodka',
            'devca': 'ca.wikitolearn.vodka',
            'devmeta': 'meta.wikitolearn.vodka',
            'devpool': 'pool.wikitolearn.vodka',
            'testit': 'it.tuttorotto.org',
            'testen': 'en.tuttorotto.org',
            'testde': 'de.tuttorotto.org',
            'testes': 'es.tuttorotto.org',
            'testfr': 'fr.tuttorotto.org',
            'testpt': 'pt.tuttorotto.org',
            'testsv': 'sv.tuttorotto.org',
            'testca': 'ca.tuttorotto.org',
            'testmeta': 'meta.tuttorotto.org',
            'testpool': 'pool.tuttorotto.org',
            'localit': 'it.tuttorotto.biz',
            'localen': 'en.tuttorotto.biz',
            'localde': 'de.tuttorotto.biz',
            'locales': 'es.tuttorotto.biz',
            'localfr': 'fr.tuttorotto.biz',
            'localpt': 'pt.tuttorotto.biz',
            'localsv': 'sv.tuttorotto.biz',
            'localca': 'ca.tuttorotto.biz',
            'localmeta': 'meta.tuttorotto.biz',
            'localpool': 'pool.tuttorotto.biz',
        }

    def scriptpath(self, code):
        return {
            'it': '',
            'en': '',
            'de': '',
            'es': '',
            'fr': '',
            'pt': '',
            'sv': '',
            'ca': '',
            'meta': '',
            'pool': '',
            'devit': '',
            'deven': '',
            'devde': '',
            'deves': '',
            'devfr': '',
            'devpt': '',
            'devsv': '',
            'devca': '',
            'devmeta': '',
            'devpool': '',
            'testit': '',
            'testen': '',
            'testde': '',
            'testes': '',
            'testfr': '',
            'testpt': '',
            'testsv': '',
            'testca': '',
            'testmeta': '',
            'testpool': '',
            'localit': '',
            'localen': '',
            'localde': '',
            'locales': '',
            'localfr': '',
            'localpt': '',
            'localsv': '',
            'localca': '',
            'localmeta': '',
            'localpool': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'it': u'1.27.0',
            'en': u'1.27.0',
            'de': u'1.27.0',
            'es': u'1.27.0',
            'fr': u'1.27.0',
            'pt': u'1.27.0',
            'sv': u'1.27.0',
            'ca': u'1.27.0',
            'meta': u'1.27.0',
            'pool': u'1.27.0',
            'devit': u'1.27.0',
            'deven': u'1.27.0',
            'devde': u'1.27.0',
            'deves': u'1.27.0',
            'devfr': u'1.27.0',
            'devpt': u'1.27.0',
            'devsv': u'1.27.0',
            'devca': u'1.27.0',
            'devmeta': u'1.27.0',
            'devpool': u'1.27.0',
            'testit': u'1.27.0',
            'testen': u'1.27.0',
            'testde': u'1.27.0',
            'testes': u'1.27.0',
            'testfr': u'1.27.0',
            'testpt': u'1.27.0',
            'testsv': u'1.27.0',
            'testca': u'1.27.0',
            'testmeta': u'1.27.0',
            'testpool': u'1.27.0',
            'localit': u'1.27.0',
            'localen': u'1.27.0',
            'localde': u'1.27.0',
            'locales': u'1.27.0',
            'localfr': u'1.27.0',
            'localpt': u'1.27.0',
            'localsv': u'1.27.0',
            'localca': u'1.27.0',
            'localmeta': u'1.27.0',
            'localpool': u'1.27.0',
        }[code]

    def protocol(self, code):
        return {
            'it': u'https',
            'en': u'https',
            'de': u'https',
            'es': u'https',
            'fr': u'https',
            'pt': u'https',
            'sv': u'https',
            'ca': u'https',
            'meta': u'https',
            'pool': u'https',
            'devit': u'https',
            'deven': u'https',
            'devde': u'https',
            'deves': u'https',
            'devfr': u'https',
            'devpt': u'https',
            'devsv': u'https',
            'devca': u'https',
            'devmeta': u'https',
            'devpool': u'https',
            'testit': u'https',
            'testen': u'https',
            'testde': u'https',
            'testes': u'https',
            'testfr': u'https',
            'testpt': u'https',
            'testsv': u'https',
            'testca': u'https',
            'testmeta': u'https',
            'testpool': u'https',
            'localit': u'https',
            'localen': u'https',
            'localde': u'https',
            'locales': u'https',
            'localfr': u'https',
            'localpt': u'https',
            'localsv': u'https',
            'localca': u'https',
            'localmeta': u'https',
            'localpool': u'https',
        }[code]
